### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by yangzhm** [openstack-freezer-utils/freezer-windows-binaries#1]
Hi @memogarcia ,
  I have a problem about build tar.exe. How can I connect you? Can you give me a Email address?

**Comment by memogarcia** [comment]
You can contact me here as well, how can I help?

**Comment by yangzhm** [comment]
@memogarcia I know how to build rpm package on linux, but I don't know how to build tar.exe on windows. Is there any tools or some scripts of building tar.exe?

**Comment by yangzhm** [comment]
@memogarcia I have built the tar.exe on windows by cygwin. Thanks any all !
